common/models/ProductTheme.php
<?php

namespace common\models;

use common\behaviors\PositionBehavior;
use common\behaviors\SoftDeleteBehavior;
use Yii;
use yii\behaviors\TimestampBehavior;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "{{%product_theme}}".
 *
 * @property integer $id
 * @property string $name
 * @property string $carousels
 * @property string $bgim
 * @property string $image
 * @property integer $city_id
 * @property integer $district_id
 * @property integer $town_id
 * @property integer $province_id
 * @property integer $village_id
 * @property integer $created_at
 * @property integer $updated_at
 * @property integer $sort
 * @property integer $status
 */
class ProductTheme extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%product_theme}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            ['name','required'],            
            [['carousels'], 'string'],
            [['city_id', 'district_id', 'town_id', 'village_id','province_id','sort'], 'integer','skipOnEmpty' => true,],
            [['name', 'bgim','image'], 'string', 'max' => 255],
            [['status'], 'string', 'max' => 3],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'positionBehavior' => [
                'class' => PositionBehavior::className(),
                'positionAttribute' => 'sort',                
            ],
			[
    			'class' => SoftDeleteBehavior::className(),
    			'softDeleteAttributeValues' => [
        					'status' => 2
        			],
    			'restoreAttributeValues' => [
        					'status' => 1
    			],
			],
            TimestampBehavior::className(),
            
        ];
    }
    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => '主题名称',
            'carousels' => '幻灯片',
            'bgim' => '背景图',
            'province_id' => '省份',
            'city_id' => '城市',
            'district_id' => '地区',
            'town_id' => '县/镇',
            'village_id' => '村',
            'created_at' => '创建时间',
            'updated_at' => '修改时间',
            'sort' => '排序',
            'status' => '状态',
            'image' => '主图',
        ];
    }
    public function beforeValidate() {
        //处理图片信息
        $images = $this->carousels;
        if(is_array($images)) {
            if (!isset($images[0]['url'])) {
                $this->addError("carousels",'必须上传一个幻灯片');
                return false;
            }
            if (strlen($images[0]['url'])==0) {
                $this->addError("carousels",'必须上传一个幻灯片');
                return false;
            }
            $images = array_filter($images);
            ArrayHelper::multisort($images,'order');
            $this->carousels = json_encode($images);
        }
        
        return parent::beforeValidate();        
    }
    public function afterFind(){
        //处理图片信息
        if (strlen($this->carousels)>0){
            $images =  $this->carousels;
            $this->carousels = json_decode($images,true);
        }
        if (count($this->carousels)<=0) {
            $this->carousels = '[{"url":"'.Yii::$app->params['defaultImg']['default'].'","thumbImg":"'.Yii::$app->params['defaultImg']['default'].'","order":"0"}]';
            $images =  $this->carousels;
            $this->carousels = json_decode($images,true);
        }
        
        
        return parent::afterFind();
    }
    
    
    
    public function getProvince(){
        return $this->hasOne(RegionLocal::class, ['id'=>'province_id']);
    }
    public function getCity(){
        return $this->hasOne(RegionLocal::class, ['id'=>'city_id']);
    }
    public function getDistrict(){
        return $this->hasOne(RegionLocal::class, ['id'=>'district_id']);
    }
    public function getTown(){
        return $this->hasOne(RegionLocal::class, ['id'=>'town_id']);
    }
    public function getVillage(){
        return $this->hasOne(RegionLocal::class, ['id'=>'village_id']);
    }
    
}

backend/controllers/ProductThemeController.php
<?php

namespace backend\controllers;

use common\logic\RegionLogic;
use common\models\ProductTheme;
use common\models\ProductThemeSearch;
use Yii;
use yii\filters\VerbFilter;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

/**
 * ProductThemeController implements the CRUD actions for ProductTheme model.
 */
class ProductThemeController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'position' => [
                'class' => 'backend\\actions\\Position',
                'returnUrl' => Url::current()
            ],'ajax-update-field' => [
                'class' => 'common\\actions\\AjaxUpdateFieldAction',
                'allowFields' => ['status'],
                'findModel' => [$this, 'findModel']
            ],
            'switcher' => [
                'class' => 'backend\widgets\grid\SwitcherAction'
            ]
        ];
    }
    /**
     * Lists all ProductTheme models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ProductThemeSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single ProductTheme model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new ProductTheme model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new ProductTheme();
        $model->loadDefaultValues();
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing ProductTheme model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing ProductTheme model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the ProductTheme model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return ProductTheme the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function findModel($id)
    {
        if (($model = ProductTheme::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
    public function actionSite($id=null, $parent_id=null,$level=null)
    {
        $regionLogic = new RegionLogic();
        $model = $regionLogic->getRegions($id,$parent_id,$level);
        
        if($level == 1){$aa="--请选择省--";}else if($level == 2){$aa="--请选择市--";}else if($level == 3){$aa="--请选择地区--";}else if($level == 4){$aa="--请选择乡镇--";}else if($level == 5){$aa="--请选择村点--";}
        
        echo Html::tag('option',$aa, ['value'=>'']) ;
        
        foreach($model as $value=>$name)
        {
            echo Html::tag('option',Html::encode($name),array('value'=>$value));
        }
    }
}

frontend/controllers/ProductThemeController.php
<?php
namespace frontend\controllers;
use Yii;
use common\models\ProductSearch;
use frontend\common\controllers\Controller;
use common\models\Carousel;
use common\models\CarouselItem;
use common\logic\ProductThemeLogic;
use common\models\ProductTheme;

class ProductThemeController extends Controller
{
    
    public function actionIndex(){
        //轮播图
      $carousel = Carousel::find()->where(array('key'=>'theme'))->one();
        $model=new CarouselItem();
        $carousels=$model->getCarousels($carousel->id,4,1);
        $productThemeLogic = new ProductThemeLogic();
        $lists = $productThemeLogic->getThemeList(8);
        return $this->render('index',
                [
                        'carousels'=>$carousels,
                        'lists'=>$lists
                ]); 
 
    }

    
    /**
     * 第一书记
     *
     * @return mixed
     */
    public function actionFirst()
    {
        $data=Yii::$app->request->get();
        $data['status']=1;
        $data['num']=10;
        $data['first']=1;
        $searchModel = new ProductSearch();
        $dataProvider = $searchModel->search($data);
        $products = $dataProvider->getModels();
        
        //轮播图
        $carousel = Carousel::find()->where(array('key'=>'frist'))->one();
        $model=new CarouselItem();
        $carousels=$model->getCarousels($carousel->id,4,1);
        return $this->render('first',[
                'carousels'=>$carousels,
                'products'=>$products,
                'num'=>$data['num'],
        ]);
    }
    

    public function actionInfo(){
        $data=Yii::$app->request->get();
        $id = $data['id'];
        $theme = ProductTheme::findOne($id);
        $data['theme_id'] = $id;
        $data['status']=1;
        $data['num']=10;
        $searchModel = new ProductSearch();
        $dataProvider = $searchModel->search($data);
        $sort = $dataProvider->getSort();
        $sort->enableMultiSort=true;
        $sort->defaultOrder = array('hot'=>SORT_DESC,'up_time'=>SORT_DESC);
        $dataProvider->setSort($sort);
        $products = $dataProvider->getModels();
        return $this->render('info',[
                'products'=>$products,
                'theme'=>$theme,
        ]
      );
    }
    
   
    
    
    
    
}

backend/views/product-theme/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use common\logic\RegionLogic;

/* @var $this yii\web\View */
/* @var $model common\models\ProductTheme */
/* @var $form yii\widgets\ActiveForm */
?>
<?php $this->registerJsFile('@web/js/jquery.bigcolorpicker.js',['depends' => 'backend\assets\AppAsset','position'=>\yii\web\View::POS_HEAD]); ?>

<div class="box box-primary">
    <div class="box-body">
    <?php $form = ActiveForm::begin([
//     			'id' => 'form-id',    			
//     			'enableAjaxValidation' => true,
     			'validateOnChange'=>false,
     			'validateOnBlur'=>false,
     			'validateOnSubmit' => true
    		]); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>
	<?php echo $form->field($model, 'image')->widget(\common\modules\attachment\widgets\SingleWidget::className(), ['onlyUrl' => true,'width'=>500,'height'=>500]) ?>
   	<?php echo $form->field($model, 'carousels')->widget(\common\modules\attachment\widgets\MultipleWidget::className(), ['onlyUrl' => true,"multiple"=>true,"sortable"=>true,'thumb'=>1,'width'=>500,'height'=>500]) ?>

    <?php // $form->field($model, 'bgim')->widget(\common\modules\attachment\widgets\SingleWidget::className(), ['onlyUrl' => true,'width'=>500,'height'=>500]) ?>
  
     <?= $form->field($model,'province_id')->dropDownList(RegionLogic::getRegions(2297),
    [
        'prompt'=>'--请选择省--',
        'onchange'=>'
            var district_id = \'<option value="">--请选择地区--</option>\';
            $("select#producttheme-district_id").html(district_id);
            var district_id = \'<option value="">--请选择乡镇--</option>\';
            $("select#producttheme-town_id").html(district_id);
            var district_id = \'<option value="">--请选择村点--</option>\';
            $("select#producttheme-village_id").html(district_id);
            $.post("'.yii::$app->urlManager->createUrl('product-theme/site').'?level=2&parent_id="+$(this).val(),function(data){
                $("select#producttheme-city_id").html(data);
            });',
    ]) ?>
    <?= $form->field($model,'city_id')->dropDownList(RegionLogic::getRegions(null,$model->province_id),
    [
        'prompt'=>'--请选择市--',
        'onchange'=>'
            var district_id = \'<option value="">--请选择乡镇--</option>\';
            $("select#producttheme-town_id").html(district_id);
            var district_id = \'<option value="">--请选择村点--</option>\';
            $("select#producttheme-village_id").html(district_id);
            $.post("'.yii::$app->urlManager->createUrl('product-theme/site').'?level=3&parent_id="+$(this).val(),function(data){
                $("select#producttheme-district_id").html(data);
            });',
    ]) ?>

	<?= $form->field($model, 'district_id')->dropDownList(RegionLogic::getRegions(null,$model->city_id),
    [
        'prompt'=>'--请选择地区--',
        'onchange'=>'
            var district_id = \'<option value="">--请选择村点--</option>\';
            $.post("'.yii::$app->urlManager->createUrl('product-theme/site').'?level=4&parent_id="+$(this).val(),function(data){
                $("select#producttheme-town_id").html(data);
            });',
    ]) ?>
    <?= $form->field($model, 'town_id')->dropDownList(RegionLogic::getRegions(null,$model->district_id),
    [
        'prompt'=>'--请选择乡镇--',
        'onchange'=>'
            ///$(".form-group.field-producttheme-town_id").show();
            $.post("'.yii::$app->urlManager->createUrl('product-theme/site').'?level=5&parent_id="+$(this).val(),function(data){
                $("select#producttheme-village_id").html(data);
            });',
    ]) ?>
      <?= $form->field($model, 'village_id')->dropDownList(RegionLogic::getRegions(null,$model->town_id),
    [
        'prompt'=>'--请选择村点--',        
            
    ]) ?>
      

    <?= $form->field($model, 'sort')->textInput() ?>

    <?= $form->field($model, 'status')->dropDownList([0=>'禁用',1=>'启用',2=>'删除']) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? '新增' : '更新', ['class' => $model->isNewRecord ? 'btn btn-success btn-flat' : 'btn btn-primary btn-flat']) ?>
    </div>

    <?php ActiveForm::end(); ?>
    </div>
</div>
<?php $this->beginBlock('block1') ?>  

<?php $this->endBlock() ?>  
<?php $this->registerJs($this->blocks['block1'], \yii\web\View::POS_END); ?>

backend/views/product-theme/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\ProductThemeSearch */
/* @var $form yii\widgets\ActiveForm */
?>
<div class="article-search">

    <?php
    Yii::$container->set(\yii\widgets\ActiveField::className(), ['template' => "{label}\n{input}"]);
    $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => ['class' => 'form-inline'],
    ]); ?>

    <?= $form->field($model, 'name') ?>
    <?= $form->field($model, 'status')->dropDownList([0=>'禁用',1=>'启用',2=>'删除'], ['prompt' => '全部','options'=>[$model->status=>['Selected'=>true]]]) ?>
    <?= Html::submitButton(Html::icon('search'), ['class' => 'btn btn-primary btn-flat']) ?>
    <div class="error-summary hide"><ul></ul></div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/product-theme/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\ProductTheme */

$this->title = '新建主题';
$this->params['breadcrumbs'][] = ['label' => '主题列表', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="product-theme-create">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/product-theme/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel common\models\ProductThemeSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = '商品主题';
$this->params['breadcrumbs'][] = $this->title;
?>
<?php $this->beginBlock('content-header') ?>
<?= $this->title . ' ' . Html::a('新建主题', ['create'], ['class' => 'btn btn-primary btn-flat btn-xs']) ?>
<?php $this->endBlock() ?>
<div class="box box-primary">
<div class="box-body">
    <?php echo $this->render('_search', ['model' => $searchModel]); ?>
    </div>
</div>
    <div class="box box-primary">
        <div class="box-body">
            <?= GridView::widget([
                'dataProvider' => $dataProvider,
                //'filterModel' => $searchModel,
        'columns' => [
                    'id',
                    'name',
                    //'carousels:ntext',
                    //'bgim',
                    //'city',
                    // 'district',
                    // 'town',
                    // 'village',
                    // 'created_at',
                    // 'updated_at',
                    [
                        'class' => 'backend\widgets\grid\SwitcherColumn',
                        'attribute' => 'status'
                    ],
                    [
                        'class' => 'backend\widgets\grid\PositionColumn',
                        'attribute' => 'sort'
                    ],

                    ['class' => 'yii\grid\ActionColumn'],
                ],
            ]); ?>
        </div>
    </div>

backend/views/product-theme/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\ProductTheme */

$this->title = '修改主题: ' . ' ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => '主题列表', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="product-theme-update">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/product-theme/view.php
<?php

use yii\helpers\Html;
use yii\helpers\Json;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\ProductTheme */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Product Themes', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="box box-primary">
    <div class="box-body">
    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'name',
            [
                'attribute' => 'carousels',
                'value' =>function($model) {
                $images = $model->carousels;
                $html = '';
                if(is_array($images)){
                    foreach ($images as $img){
                        $imgHtml = Html::img($img['url'],['width'=>'100px']);
                        $html = $html.$imgHtml;
                    }}
                    return $html;
                },
                'format' => ['html'],
                ],
                [
                    'attribute' => 'bgim',
                    'value' =>function($model) {
                        $images = $model->bgim;
                        $html = '';
                        $imgHtml = Html::img($images,['width'=>'100px']);
                        $html = $html.$imgHtml;
                        return $html;
                    },
                    'format' => ['html'],
                    ],
                [
                    'attribute' => 'image',
                    'value' =>function($model) {
                    $images = $model->image;
                    $html = '';
                    $imgHtml = Html::img($images,['width'=>'100px']);
                    $html = $html.$imgHtml;
                    return $html;
                    },
                    'format' => ['html'],
                    ],
                [
                    'label'=>'所属省份',
                    'attribute'=>'province.name'
                ],
                [
                    'label'=>'所属城市',
                    'attribute'=>'city.name'
                ],
                [
                    'label'=>'所属地区',
                    'attribute'=>'district.name'
                ],
                [
                    'label'=>'所属乡镇',
                    'attribute'=>'town.name'
                ],
                [
                    'label'=>'所属村点',
                    'attribute'=>'village.name'
                ],
                            
            'created_at:datetime',
            'updated_at:datetime',
            'sort',
            'status',
        ],
    ]) ?>
    </div>
</div>