backend/models/Member.php
<?php
class Member extends \common\models\Member{
    
    public $verifyPassword;
    
    public function rules(){
        return [
            ['username', 'string', 'on' => 'search'],
            ['username', 'required', 'on' => 'create'],
            ['username', 'unique', 'on' => 'create'],
            ['email', 'required', 'on' => 'create'],
            ['email', 'unique', 'on' => 'create'],
            ['password', 'required', 'on' => ['register']],
        ];
    }
    
    public function scenarios()
    {
        $scenarios = parent::scenarios();
        return array_merge($scenarios, [
            'register' => ['username', 'email', 'password'],
            'connect'  => ['username', 'email'],
            'create'   => ['username', 'email', 'password'],
            'update'   => ['username', 'email', 'password'],
            'settings' => ['username', 'email', 'password'],
            'resetPassword' => ['password']
        ]);
    }
}

backend/controllers/MemberController.php
<?php

namespace backend\controllers;

use common\models\Member;

use Yii;
use yii\data\ActiveDataProvider;
use yii\filters\VerbFilter;
use Distill\Exception\IO\Exception;
use backend\common\controllers\Controller;
use yii\web\NotFoundHttpException;
use common\models\MemberSearch;
use common\models\TpUsers;

class MemberController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }
    
    public function actions()
    {
        return [
            
            'ajax-update-field' => [
                'class' => 'common\\actions\\AjaxUpdateFieldAction',
                'allowFields' => ['status'],
                'findModel' => [$this, 'findModel']
            ],
            'switcher' => [
                'class' => 'backend\widgets\grid\SwitcherAction'
            ]
        ];
    }

    public function actionIndex()
    {
        $searchModel = new MemberSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]); 
    }
    
    public function actionList()
    {
        $searchModel = new MemberSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        
        return $this->render('list', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
    
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    public function actionCreate()
    {
        $model = new Member(['scenario' => 'create']);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

//     public function actionDelete($id)
//     {
//         $this->findModel($id)->delete();

//         return $this->redirect(['index']);
//     }
    
    public function findModel($id)
    {
        if (($model = Member::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
    
//     public function actionQianyi(){
//         $success = array();
//         $errors = array();
//         $users = TpUsers::find()->where(['>','user_id',4499])->andWhere(['<','user_id',7000])->all();
//         foreach ($users as $u)
//         {
//             $member = new Member();
//             $member->loadDefaultValues();
//             $member->id = $u->user_id;
//             $member->username = $u->nickname;            
//             $member->mobile = $u->mobile;
//             $member->mobile_validated = $u->mobile_validated;
//             $member->password = $u->password;
//             //$member->auth_key = $u->;
//             //$member->xcx_openid = $u->xc;            
//             $member->wx_openid = $u->openid;
//             //$member->avatar = $u->head_pic;
//             $member->avatarUrl = $u->head_pic;
//             $member->email = $u->email;
//             $member->email_validated = $u->email_validated;
//             if ($u->sex==1) {
//                 $member->sex = '男';
//             }elseif ($u->sex==2){
//                 $member->sex = '女';
//             }else{
//                 $member->sex = '保密';
//             }            
//             //$member->age = $u->ag;
//             //$member->province = $u->province;            
//             //$member->city = $u->city;            
//             $member->score = $u->pay_points;
//             $member->level = $u->level;
//             $member->status = $u->is_lock;
//             $member->register_time = $u->reg_time;
//             $member->last_login = $u->last_login;
//             //$member->access_token = $u->token;
//             //$member->expire_in = $u->ex;
//             //$member->oauth_id = $u->user_id;
//             //$member->flag = $u->user_id;
//             $member->pay_pwd = $u->paypwd;
//             $member->user_money = $u->user_money;
//             $member->frozen_money = $u->frozen_money;
//             $member->distribut_money = $u->distribut_money;
//             //$member->underling_number = $u->un;
//             $member->total_amount = $u->total_amount;
//             $member->is_distribut = $u->is_distribut;
//             //$member->distribut_level = $u->dis;
//             $member->first_leader = $u->first_leader;
//             $member->second_leader = $u->second_leader;
//             $member->third_leader = $u->third_leader;
//             //$member->message_mask = $u->me;
//             //$member->push_id = $u->user_id;
//             //$member->is_vip = $u->is;
//             //$member->version = $u->user_id;
//             //$member->type = $u->user_id;
//             try {
//                 if (!$member->save()) {
                   
//                     $arr = array();
//                     $arr['id'] = $u->user_id;
//                     $arr['err'] = $member->getErrors();
//                     array_push($errors, $arr);
//                 }  
//             } catch (Exception $e) {
//                 $arr = array();
//                 $arr['msg'] = $u->user_id;
//                 array_push($errors, $e->getMessage());
//             }
                      
//         }
//         var_dump($errors);
//     }

    /**
     * Updates an existing Emp model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionPwd($id)
    {
        $model = $this->findModel($id);
        $model->setScenario("pwd");
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('pwd', [
                'model' => $model,
            ]);
        }
    }
    
}

frontend/controllers/MemberController.php
<?php
/**
 * 
 * Author wsyone wsyone@faxmail.com   pengpeng 617191460@qq.com
 * Time:2018年11月16日 下午3:04:21
 * Copyright:广西几何线科技有限公司
 * site:https://www.jihexian.com
 */
namespace frontend\controllers;
use Yii;
use yii\data\ActiveDataProvider;
use frontend\common\controllers\Controller;
use common\models\Member;
use common\models\Shop;
use yii\helpers\Json;
use yii\helpers\Url;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use common\models\Plugin;
use common\models\Recharge;
use common\models\Collection;
use common\models\CollectionSearch;
use common\models\AccountLogSearch;
use common\models\CollectionShopSearch;
use common\models\ShopUser;
use common\models\SmsLog;
use frontend\models\RegisterForm;
use yii\web\Response;
use yii\widgets\ActiveForm;
use frontend\models\ResetPasswordForm;
use frontend\models\BindMobileForm;
use yii\helpers\ArrayHelper;
use yii\rest\Serializer;
use common\helpers\Tools;
use frontend\models\ResetPayPasswordForm;
use common\models\ShopCategory;
use frontend\models\UnbindMobileForm;

use frontend\models\BindInfoForm;

use common\models\WithdrawalSearch;
use common\models\Withdrawal;
use common\logic\WithdrawalLogic;
use function GuzzleHttp\json_encode;
use common\models\RegisterShop;


/**
 * Member controller.
 */
class MemberController extends Controller
{
//     public function init(){
//         if (empty(Yii::$app->user->identity->mobile))
//         parent::init();
//     }
    
    
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [                   
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['reset-password'],
                        'roles' => ['?','@'],
                    ],
                ],
            ],
        ];
    }
    /**
     * 我的主页.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        $memberId=Yii::$app->user->id;
        $member = Member::findOne(['id'=>$memberId]);
        $user=ShopUser::find()->where(['m_id'=>$memberId])->one();
        $shop=Shop::find()->where(['id'=>$user['shop_id']])->one();
        return $this->render('index',[           
            'item'=>$member,
            'shop'=>$shop,

        ]);
    }
    
    public function actionResetPayPassword(){
        $m_id=Yii::$app->user->id;
        $data=Member::find()->where(['id'=>$m_id])->asArray()->one();
        $model = new ResetPayPasswordForm();
        if(\Yii::$app->request->isPost){
            if ($model->load(Yii::$app->request->post())) {
                if (Yii::$app->request->isAjax) {
                    Yii::$app->response->format = Response::FORMAT_JSON;
                    return ActiveForm::validate($model);
                }
                if ($user = $model->resetpaypassword()) {
                    return $this->goHome();
                }
            }
        }
        return $this->render('reset_pay_password', ['model' => $model,'data'=>$data]);
    }
    
    
    
    public function actionAnquan(){
        return $this->render('anquan');
    }
    /**
     * @desc 申请店铺
     * @return string
     */
    public function actionApply(){
        $model=ShopCategory::find()->where(['status'=>1])->orderBy('sort asc')->all();
        return $this->render('apply',[
            'model'=>$model,
        ]);
    }
    public function actionApplyPost(){
        $data=yii::$app->request->post();
        $shop=Shop::findOne(['member_id'=>yii::$app->user->id,'mobile'=>$data['mobile']]);
        $truncation=yii::$app->db->beginTransaction();
        try {
            if(!empty($shop)){
                if(!$shop->delete()){
                    $truncation->rollBack();
                    return json_encode(['status'=>0,'msg'=>'操作失败']);
                }
            }
            $shopcategory=ShopCategory::find()->where(['name'=>\Yii::$app->request->post('category_id')])->one();
            $data['member_id']=yii::$app->user->id;
            $data['category_id']=$shopcategory['id'];
            $register=new RegisterShop();
            if(!$register->load($data,'')||!$register->signup()){
                $truncation->rollBack();
                return json_encode(current($register->getFirstErrors()));
            }
            $truncation->commit();
            return json_encode(['status'=>1,'msg'=>'申请成功']);
            
        } catch (\Exception $e) {
            $truncation->rollBack();
            return json_encode(['status'=>0,'msg'=>'操作失败']);
        }
    }
     
    private function checksms($mobile,$code){
        $sms = SmsLog::find()->where(['mobile'=>$mobile,'scene'=>1,'code'=>$code])->one();
        if (empty($sms)) {
            return ['status'=>0,'msg'=>'验证码错误！'];
        }else{
            if ($sms->created_at>time()+60*10*1000) {
                return ['status'=>0,'msg'=>'验证码过期，请重新获取！'];
                
            }else{
                return ['status'=>1,'msg'=>'成功'];
            }
        }
    }
  
    
/*     public function actionApply(){
        if(Yii::$app->request->post()){
            $model=new ShopApply();
            $model->load(Yii::$app->request->post());
            $model->save();
            if($model->hasErrors()) {
                throw new \Exception('操作失败');
            }
  
        }else{
            $model=new ShopApply();
            
            return $this->render('apply',[
                'model'=>$model,
            ]);
        }
    } */ 
    /**
     *@desc 积分流水
     */
    public function actionScoreLog(){
        $memberId=Yii::$app->user->id;
        $member = Member::findOne(['id'=>$memberId]);
        $data=Yii::$app->request->post();
        $data['member_id']=$memberId;
        $data['change_type']=1;
        $data['num']=10;
        $searchModel = new AccountLogSearch();
        $dataProvider = $searchModel->search($data);  
        $sort = $dataProvider->getSort();
        $sort->enableMultiSort=true;
        $sort->defaultOrder = array('id'=>SORT_DESC);
        $dataProvider->setSort($sort);
        $log=$dataProvider->getModels();
        if(Yii::$app->request->isPost){
            $serializer = new Serializer();
            $pagecount=$dataProvider->getTotalCount();
            $pagecount=ceil($pagecount/$data['num']);
            return Json::encode(ArrayHelper::merge(['items'=>$serializer->serialize($dataProvider)], ['pagecount'=>$pagecount]));
        }else{
            return $this->render('score_log',[
                    'score'=>$member['score'],
                    'log'=>$log,
            ]);
        } 
    }
    
    /**
     * 钱包
     * @return string
     */ 
    public function actionWallet(){

       $m_id = Yii::$app->user->id;
       $member = Member::findOne(['id'=>$m_id]);  
        
         return $this->render('wallet',[
            'money'=>$member['user_money'],     
        ]); 
    }
    
    /**
     * 提现
     */
    
    public function actionWithdrawal(){

        if(yii::$app->request->isPost){
            $data=array();
            $wx_openid=Yii::$app->session->get('wx_openid');
            $post=yii::$app->request->post();
            if (!empty($wx_openid) && strstr($_SERVER['HTTP_USER_AGENT'], 'MicroMessenger')) {
                $client='weixin';
                $payment=Plugin::find()->where(['id'=>'weixin','status'=>1])->one();
                if(empty($payment)){
                    return yii::$app->session->set('error','请先到后台插件控制台开启微信支付功能');
                }
            }else{
                $client='normal';
                $payment=array();
                $data['bank_name']=$post['Withdrawal']['bank_name'];
                $data['bank_card']=$post['Withdrawal']['bank_card'];
                $data['realname']=$post['Withdrawal']['realname'];
            }
            
            $money=$post['Withdrawal']['pay_amount'];
            $logic = new WithdrawalLogic();
            $mid = yii::$app->user->id;
            $data = $logic->apply($money, $mid, $client,0,$data);
            if($data['status']==0){
               yii::$app->session->set('error',$data['msg']);
               return $this->goBack();
                
            }else{
                yii::$app->session->set('success','申请成功，等待管理员审核');
                return $this->redirect(['member/wallet']);
            }
  
        }else{
            $m_id = Yii::$app->user->id;
            $model=new Withdrawal();
            $model->setScenario('bank_create');
            $member = Member::findOne(['id'=>$m_id]);
            $wx_openid=Yii::$app->session->get('wx_openid');
            $searchModel = new WithdrawalSearch();
            $con['num']=8;
            $con['m_id']=$m_id;
            $dataProvider = $searchModel->search($con);
            $log=$dataProvider->getModels();
     
            if (!empty($wx_openid) && strstr($_SERVER['HTTP_USER_AGENT'], 'MicroMessenger')) {
                return $this->render('withdrawal',[
                        'member'=>$member,
                        'model'=>$model,
                        'log'=>$log,
                ]);
            }else{
                return $this->render('withdrawal_normal',[
                        'member'=>$member,
                        'model'=>$model,
                        'log'=>$log,
                ]);
            }  
        }
    }
  

    
    /**
     * 账户提现记录
     */
    public function actionWithdrawalLog(){
        $data=Yii::$app->request->post();
        $data['m_id']=Yii::$app->user->id;     
        $searchModel = new WithdrawalSearch();
        $dataProvider = $searchModel->search($data); 
        return $dataProvider;
    }
    
    public function actionRecharge(){
        $model=new Recharge();

backend/views/member/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use common\models\MemberLevel;
use yii\helpers\ArrayHelper;
/* @var $this yii\web\View */
/* @var $model common\models\Member */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="box box-primary">
    <div class="box-body">
    <?php $form = ActiveForm::begin(); ?>
    <?php if($model->isNewRecord){$model->sex = '男';$model->status = 1;}?>
    <?= $form->field($model, 'username')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'mobile')->textInput(['maxlength' => true]) ?>    
    
    <?= $form->field($model, 'sex')->radioList(['男' => '男', '女' => '女'], ['style' => 'padding-top: 5px;'])->label('性别') ?>

    <?= $form->field($model, 'age')->textInput() ?>


    <?= $form->field($model, 'level')->dropDownList(ArrayHelper::map(MemberLevel::GetParentOrderBySort(),'id','name')) ?>

    <?=$form->field($model, 'type')->dropDownList([
                '1' => '个人',
                '2' => '机关单位',
                '3'=>'站长'
        ])?>
    <?= $form->field($model, 'status')->radioList(['1' => '启用', '0' => '禁用'], ['style' => 'padding-top: 5px;'])->label('状态') ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? '新增' : '修改', ['class' => $model->isNewRecord ? 'btn btn-success btn-flat' : 'btn btn-primary btn-flat']) ?>
    </div>

    <?php ActiveForm::end(); ?>
    </div>
</div>

backend/views/member/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\MemberSearch */
/* @var $form yii\widgets\ActiveForm */
?>
<div class="article-search">

    <?php
    Yii::$container->set(\yii\widgets\ActiveField::className(), ['template' => "{label}\n{input}"]);
    $form = ActiveForm::begin([
        'action' => [''],
        'method' => 'get',
        'options' => ['class' => 'form-inline'],
    ]); ?>
    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'username') ?>

    <?= $form->field($model, 'mobile') ?>
    
    <?= Html::submitButton(Html::icon('search'), ['class' => 'btn btn-primary btn-flat']) ?>
    <div class="error-summary hide"><ul></ul></div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/member/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\Member */

$this->title = '添加会员';
$this->params['breadcrumbs'][] = ['label' => 'Members', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="member-create">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/member/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = '会员列表';
$this->params['breadcrumbs'][] = $this->title;
?>
<?php $this->beginBlock('content-header') ?>
<?= $this->title . ' ' . Html::a('添加会员', ['create'], ['class' => 'btn btn-primary btn-flat btn-xs']) ?>
<?php $this->endBlock() ?>
	<div class="box box-primary">
        <div class="box-body"><?php echo $this->render('_search', ['model' => $searchModel]); ?></div>
    </div>
    <div class="box box-primary">
        <div class="box-body">
            <?= GridView::widget([
                'dataProvider' => $dataProvider,
                'columns' => [
                    'id',
                    'username',
                    'mobile',
                    //'email',
                    'sex',
                    //'age',
                    'score',
                    'user_money',
                    [
					'attribute' => 'type',
                     'value'=>function($model){
                            return $model->renderType();
                            },
					'label' => '会员类型',
					],
                    [
                        'class' => 'backend\widgets\grid\SwitcherColumn',
                        'attribute' => 'status'
                    ],
                  
                    //'register_time:datetime',
                    //'last_login:datetime',
                    ['class' => 'yii\grid\ActionColumn',
                        'template' => '{view}'.' '.'{update}'.' '.' '.'{pwd}',
                        'buttons' => [
                          
                            'pwd' => function($url, $model, $key) {
                                return Html::a('改密', null, ['class' => 'btn btn-xs btn-default','data-toggle' => 'tooltip','href'=>Url::to(['member/pwd','id'=>$model->id]),'title' => '改密 ']);
                            }
                            ]
                        ],
                ],
            ]); ?>
        </div>
    </div>

backend/views/member/list.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = '会员列表';
$this->params['breadcrumbs'][] = $this->title;
?>
<?php $this->beginBlock('content-header') ?>
<?php $this->endBlock() ?>
	<div class="box box-primary">
        <div class="box-body"><?php echo $this->render('_search', ['model' => $searchModel]); ?></div>
    </div>
    <div class="box box-primary">
        <div class="box-body">
            <?= GridView::widget([
                'dataProvider' => $dataProvider,
                'columns' => [
                    [
                        'class' => 'yii\grid\RadioButtonColumn',
                     ],
                    'id',
                    'username',
                    'mobile',
                    //'email',
                    'sex',
                    //'age',
                    'score',
                    'user_money',
                    [
					'attribute' => 'type',
                     'value'=>function($model){
                            return $model->renderType();
                            },
					'label' => '用户类型',
					],
                 
                    //'register_time:datetime',
                    //'last_login:datetime',
                 
                ],
            ]); ?>
        </div>
        <div class="form-group save-box">
                    <button type="submit" class="btn btn-primary btn-flat" onclick="select_member();">确定</button>              
                </div>
    </div>
    
    <?php $this->beginBlock('specification') ?>  
     var user = null;
     function select_member(){
      var input = $("input[type='radio']:checked");
        if (input.length == 0) {
           alert('请选择用户'); 
           return false;
        }
        window.parent.call_back(user);
    }
       //商品product对象
    function User(user_id, name) {
        this.user_id = user_id;
        this.name = name;

    }
       $("input[type='radio']").click(function(){
    	var user_id = $(this).val();
    	if(user==null||user.user_id!=user_id){
    		var name = $(this).parent('td').siblings('td').eq(1).text();
    		user = new User(user_id, name);
    	}     
    })   
   

    <?php $this->endBlock() ?> 
	<?php $this->registerJs($this->blocks['specification'], \yii\web\View::POS_END); ?>

backend/views/member/pwd.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\Member */
/* @var $form yii\widgets\ActiveForm */
$this->title = '改密: ' . ' ' . $model->username;
$this->params['breadcrumbs'][] = ['label' => '会员列表', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->username, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = '改密';
?>


<div class="box box-primary">
    <div class="box-body">
    <?php $form = ActiveForm::begin(); ?>

    
	<?= $form->field($model, 'password')->passwordInput(['maxlength' => true]) ?>
	
	
    <div class="form-group">
        <?= Html::submitButton('更新', ['class' => $model->isNewRecord ? 'btn btn-success btn-flat' : 'btn btn-primary btn-flat']) ?>
    </div>

    <?php ActiveForm::end(); ?>
    </div>
</div>

backend/views/member/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Member */

$this->title = '更新会员信息: ' . ' ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => '会员列表', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = '更新';
?>
<div class="member-update">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/member/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\Member */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => '会员列表', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="box box-primary">
    <div class="box-body">
    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'username',
            'mobile',
            //'password',
            //'xcx_openid',
            //'wx_openid',
            'sex',
            'age',
            'score',
            'user_money',
            'memberLevel.name',
            [
                'attribute' => 'avatarUrl',
                'value' =>function($model) {
                    $image = $model->avatarUrl;               
                    return Html::img($image,['width'=>'100px']);
                },
                'format' => ['html'],
                ],
            'register_time:datetime',
            'last_login:datetime',
        ],
    ]) ?>
    </div>
</div>